package transacciones.model;
// Generated 18/02/2013 02:39:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Recibos generated by hbm2java
 */
public class Recibos  implements java.io.Serializable {


     private int id;
     private String tipo;
     private Date fecha1;
     private Date fecha2;
     private String estado;
     private String cedula;
     private String monto;

    public Recibos() {
        id =0;
        tipo="";
        fecha1 = new Date();
        fecha2 = new Date();
        estado ="";
        cedula="";
        monto="";
        
                
    }

	
    public Recibos(int id) {
        this.id = id;
    }
    public Recibos(int id, String tipo, Date fecha1, Date fecha2, String estado, String cedula, String monto) {
       this.id = id;
       this.tipo = tipo;
       this.fecha1 = fecha1;
       this.fecha2 = fecha2;
       this.estado = estado;
       this.cedula = cedula;
       this.monto = monto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha1() {
        return this.fecha1;
    }
    
    public void setFecha1(Date fecha1) {
        this.fecha1 = fecha1;
    }
    public Date getFecha2() {
        return this.fecha2;
    }
    
    public void setFecha2(Date fecha2) {
        this.fecha2 = fecha2;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }




}


