package transacciones.model;
// Generated 18/02/2013 02:39:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetas generated by hbm2java
 */
public class Tarjetas  implements java.io.Serializable {


     private String numero;
     private Usuario usuario;
     private Date fechavencimiento;
     private Date fechaemision;
     private BigDecimal limite;
     private Set transaccioneses = new HashSet(0);
     public double saldo;

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public double getSaldo() {
        return saldo;
    }

    public Tarjetas() {
    }

	
    public Tarjetas(String numero) {
        this.numero = numero;
    }
    public Tarjetas(String numero, Usuario usuario, Date fechavencimiento, Date fechaemision, BigDecimal limite, Set transaccioneses) {
       this.numero = numero;
       this.usuario = usuario;
       this.fechavencimiento = fechavencimiento;
       this.fechaemision = fechaemision;
       this.limite = limite;
       this.transaccioneses = transaccioneses;
    }
   
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public BigDecimal getLimite() {
        return this.limite;
    }
    
    public void setLimite(BigDecimal limite) {
        this.limite = limite;
    }
    public Set getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set transaccioneses) {
        this.transaccioneses = transaccioneses;
    }




}


