package transacciones.model;
// Generated 18/02/2013 02:39:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Transacciones generated by hbm2java
 */
public class Transacciones  implements java.io.Serializable {


     private int id;
     private Tarjetas tarjetas;
     private String tipo;
     private Date fecha;
     private String descripcion;
     private Double monto;

    public Transacciones() {
    }

	
    public Transacciones(int id) {
        this.id = id;
    }
    public Transacciones(int id, Tarjetas tarjetas, String tipo, Date fecha, String descripcion, Double monto) {
       this.id = id;
       this.tarjetas = tarjetas;
       this.tipo = tipo;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.monto = monto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tarjetas getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Tarjetas tarjetas) {
        this.tarjetas = tarjetas;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


